services:
  database:
    image: postgres:17
    container_name: swiftcodes_db
    restart: always
    environment:
      POSTGRES_DB: swift_codes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backup.dump:/docker-entrypoint-initdb.d/backup.dump  # Automatyczne przywracanie bazy

  app:
    build: .
    container_name: swiftcodes_app
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/swift_codes_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"

volumes:
  db_data:
